"""Unit tests for state.py."""
import os
import pytest
from pathlib import Path

import state as state_module
from state import write_state, load_state, STATE_FILE


@pytest.fixture(autouse=True)
def isolated_dir(tmp_path, monkeypatch):
    """Run every test in a fresh temp directory so state files don't collide."""
    monkeypatch.chdir(tmp_path)


# ---------------------------------------------------------------------------
# write_state
# ---------------------------------------------------------------------------

class TestWriteState:
    def test_creates_file(self):
        write_state("ABC-1", "feature/ABC-1")
        assert Path(STATE_FILE).exists()

    def test_content_ticket_and_branch(self):
        write_state("TST-99", "feature/TST-99")
        text = Path(STATE_FILE).read_text()
        assert "ticket: TST-99" in text
        assert "branch: feature/TST-99" in text

    def test_base_override_none_writes_null(self):
        write_state("X-1", "feature/X-1", base_override=None)
        text = Path(STATE_FILE).read_text()
        assert "base_override: null" in text

    def test_base_override_string_written(self):
        write_state("X-1", "feature/X-1", base_override="develop")
        text = Path(STATE_FILE).read_text()
        assert "base_override: develop" in text

    def test_overwrites_existing_file(self):
        write_state("OLD-1", "feature/OLD-1")
        write_state("NEW-2", "feature/NEW-2")
        text = Path(STATE_FILE).read_text()
        assert "NEW-2" in text
        assert "OLD-1" not in text


# ---------------------------------------------------------------------------
# load_state
# ---------------------------------------------------------------------------

class TestLoadState:
    def test_missing_file_exits(self):
        with pytest.raises(SystemExit):
            load_state()

    def test_round_trip(self):
        write_state("ABC-42", "feature/ABC-42")
        s = load_state()
        assert s["ticket"] == "ABC-42"
        assert s["branch"] == "feature/ABC-42"

    def test_base_override_null_becomes_none(self):
        write_state("X-1", "feature/X-1", base_override=None)
        s = load_state()
        assert s["base_override"] is None

    def test_base_override_value_round_trips(self):
        write_state("X-1", "feature/X-1", base_override="develop")
        s = load_state()
        assert s["base_override"] == "develop"

    def test_missing_ticket_field_exits(self, tmp_path):
        Path(STATE_FILE).write_text("branch: feature/X-1\nbase_override: null\n")
        with pytest.raises(SystemExit):
            load_state()

    def test_missing_branch_field_exits(self, tmp_path):
        Path(STATE_FILE).write_text("ticket: X-1\nbase_override: null\n")
        with pytest.raises(SystemExit):
            load_state()

    def test_comment_lines_ignored(self):
        Path(STATE_FILE).write_text(
            "# generated by devctl\n"
            "ticket: COM-1\n"
            "branch: feature/COM-1\n"
            "base_override: null\n"
        )
        s = load_state()
        assert s["ticket"] == "COM-1"

    def test_empty_file_exits(self):
        Path(STATE_FILE).write_text("")
        with pytest.raises(SystemExit):
            load_state()
